compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: 4
  gradient_clipping: 1.0
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
  same_network:
distributed_type: DEEPSPEED
fsdp_config: { }
main_training_function: main
mixed_precision: fp16
num_machines: 8
num_processes: 8
use_cpu: false